version: "3.3"
    
services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    depends_on:
      - db
    networks:
      wp:
    environment:
      PMA_HOST: db
      PMA_USER: $db_user
      PMA_PASSWORD: $db_password
      MYSQL_ROOT_PASSWORD: $db_root_password
